# Generated by Django 3.0.6 on 2020-05-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='redditdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('all_date', models.TextField(blank=True, null=True)),
                ('score', models.TextField(blank=True, null=True)),
                ('id_id', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('created', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
